### ISSUE TITLE
Regarding Contribution

### ISSUE THREAD

**Issue by sanjayy-22** [wass08/r3f-ai-language-teacher#3]
Hi sir, can I be the contributor of the project?? I have added the free open-router API and also Lovo instead of the OpenAI API key and Azure TTS.

**Comment by wass08** [comment]
Hey, @sanjayy-22, thanks for the work, can you do a pull-request? 
As this code is the one from the video tutorial, please ensure you don't replace the OpenAI Api / Azure TTS code but make a mechanism to switch between different providers through parameters or environment variables.

**Comment by sanjayy-22** [comment]
@wass08 I have given the pull request sir!
